### ISSUE TITLE
[UI Revamp] Auction listing 

### ISSUE THREAD

**Issue by MehulKChaudhari** [Real-Dev-Squad/website-crypto#297]
### Expectation

* Without changing or with minimum change on functionality, closely align the UI as per [Figma](https://www.figma.com/file/9t1Zr4PGQL4UWSIpeh4RMY/RDS?node-id=0%3A1&t=RLiIlpzU3voEjvTW-3)
<img width="688" alt="Screenshot 2022-12-11 at 4 05 41 PM" src="https://user-images.githubusercontent.com/55375534/206898868-43c86644-d642-4155-b8e6-6336773e3524.png">

**Comment by ranitasahaa1230** [comment]
@MehulKChaudhari, Please assign this to me.

**Comment by bajajcodes** [comment]
@MehulKChaudhari please assign this issue to me.
cc: @prakashchoudhary07 @ranitasahaa1230

**Comment by MehulKChaudhari** [comment]
> @MehulKChaudhari please assign this issue to me. cc: @prakashchoudhary07 @ranitasahaa1230

Done.

**Comment by bajajcodes** [comment]
`Update:` 
[13-02-23] Started Working on the issue but got the error message: **Request failed to proxy: ECONNREFUSED** on visiting `dev.realdevsquad.com` using local-ssl-proxy.
Discord Server: [Issue Refference](https://discord.com/channels/673083527624916993/748267291405320204/1074494444650364948)
[16-03-23] Blocker not resolved, but will try to close PR using backend on localhost.
[17-03-23] Starting working on new design of auctions page and draft PR raised.
[19-03-23] PR is Ready for Review.
